source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.1"
xcodeproj '虾逛.xcodeproj'
pod 'Mapbox-iOS-SDK',:git => 'https://github.com/robotaoyuan/mapbox-ios-sdk'
pod 'EstimoteSDK','2.1.5'
pod 'AVOSCloud','2.6.6'
pod 'FMDB','2.3'
pod 'pop','1.0.7'
pod 'MMProgressHUD','0.2.3'
pod 'Reachability','3.1.1'
pod 'UnrarKit','2.2.3'
pod 'FCFileManager','1.0.6'
pod 'PESGraph','0.2.1'
