source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.1"
xcodeproj '虾逛.xcodeproj'
pod 'Mapbox-iOS-SDK',:git => 'https://github.com/robotaoyuan/mapbox-ios-sdk'
pod 'EstimoteSDK','2.1.5'
pod 'AVOSCloud','2.6.6'
pod 'FMDB','2.3'
pod 'Reachability','3.1.1'
pod 'PESGraph','0.2.1'
pod 'AFNetworking', '~>2.5'
pod 'zipzap','8.0.1'
